version: "3.8"
services:
  eve-chainkills:
    build: .
    volumes: 
      - .:/app
      - .:/app/node_modules
    container_name: eve-chainkills
    networks:
      - default
      - web
networks:
  default:
    external:
      name: pathfinder-containers_pf
  web: 
    external: true
